import type { CCFEvent, PastoralRep } from './types';

export const MOCK_EVENTS: CCFEvent[] = [
  {
    id: 'EVT-001',
    title: 'Elevate Friday Night',
    description: 'Weekly worship and small group night for young professionals. First-timers very welcome!',
    ministry: 'Elevate',
    division: 'Ministries',
    journey_stage: 'Engage',
    start_datetime: '2026-05-15T19:00:00+08:00',
    end_datetime: '2026-05-15T21:30:00+08:00',
    venue: 'CCF Main, Multi-Purpose Hall 2',
    is_online: false,
    cost: 'Free',
    capacity: 200,
    registration_link: 'https://ccf.org.ph/elevate',
    contact_person: 'Kuya Mark Santos',
    contact_number: '+639171234567',
    next_step_type: 'register_online',
    is_featured: true,
    status: 'Published',
  },
  {
    id: 'EVT-002',
    title: 'WOW Wednesday Bible Study',
    description: 'Women of the Word weekly Bible study. Open to all women, all life stages.',
    ministry: 'WOW',
    division: 'Ministries',
    journey_stage: 'Edify',
    start_datetime: '2026-05-13T09:30:00+08:00',
    end_datetime: '2026-05-13T11:30:00+08:00',
    venue: 'CCF Main, Prayer Hall',
    is_online: false,
    cost: 'Free',
    capacity: 150,
    contact_person: 'Ate Grace Lim',
    contact_number: '+639181234567',
    next_step_type: 'visit_booth',
    is_featured: false,
    status: 'Published',
  },
  {
    id: 'EVT-003',
    title: 'GLC 1',
    description: 'Foundational Dgroup grounding — 10-week journey through core discipleship principles.',
    ministry: 'GLC',
    division: 'GLC',
    journey_stage: 'Edify',
    start_datetime: '2026-06-01T19:00:00+08:00',
    end_datetime: '2026-06-01T21:00:00+08:00',
    venue: 'CCF Main, GLC Room',
    is_online: false,
    cost: 'Free',
    capacity: 30,
    registration_link: 'https://ccf.org.ph/glc',
    contact_person: 'Ptr. Boni Tan',
    contact_number: '+639221234567',
    next_step_type: 'register_online',
    is_featured: true,
    status: 'Published',
  },
  {
    id: 'EVT-004',
    title: 'Marriage Enrichment Retreat',
    description: '2-day overnight retreat for married couples. Strengthen your marriage through God\'s Word.',
    ministry: 'Couples Retreat',
    division: 'Ministries',
    journey_stage: 'Edify',
    start_datetime: '2026-06-14T15:00:00+08:00',
    end_datetime: '2026-06-15T16:00:00+08:00',
    venue: 'Tagaytay Highlands',
    is_online: false,
    cost: 'PHP 8,500',
    capacity: 40,
    registration_link: 'https://ccf.org.ph/couples-retreat',
    contact_person: 'Ptr. Allan & Tess Cruz',
    contact_number: '+639211234567',
    next_step_type: 'pay_at_booth',
    is_featured: true,
    status: 'Published',
  },
  {
    id: 'EVT-005',
    title: "Ptr Erwin Elevazo Pastoral Area Gathering",
    description: 'Pastoral Area Gathering with Ptr Erwin Elevazo & Ptr Ito De Jesus. Theme: Evangelifestyle.',
    ministry: 'Unite',
    pastoral_area: 'Ptr Erwin Elevazo PA',
    division: 'Pastoral Areas',
    journey_stage: 'Edify',
    start_datetime: '2026-05-23T13:00:00+08:00',
    end_datetime: '2026-05-23T16:00:00+08:00',
    venue: 'CCF Center, Multi-Purpose Hall',
    is_online: false,
    cost: 'Free',
    contact_person: 'PA Coordinator',
    contact_number: '+639231234567',
    next_step_type: 'call_pastoral_rep',
    is_featured: false,
    status: 'Published',
  },
  {
    id: 'EVT-006',
    title: "Men's Breakfast Fellowship",
    description: 'Monthly men\'s gathering with breakfast, message, and small group huddles.',
    ministry: "Men's Movement",
    division: 'Ministries',
    journey_stage: 'Engage',
    start_datetime: '2026-05-24T07:00:00+08:00',
    end_datetime: '2026-05-24T09:30:00+08:00',
    venue: 'CCF Main, Function Hall',
    is_online: false,
    cost: 'PHP 200',
    capacity: 100,
    contact_person: 'Kuya Rey Bautista',
    contact_number: '+639201234567',
    next_step_type: 'pay_at_booth',
    is_featured: false,
    status: 'Published',
  },
  {
    id: 'EVT-007',
    title: 'ACROSS Mission Orientation',
    description: 'Introduction to cross-cultural missions and ACROSS opportunities.',
    ministry: 'ACROSS',
    division: 'Ministries',
    journey_stage: 'Equip',
    start_datetime: '2026-05-31T14:00:00+08:00',
    end_datetime: '2026-05-31T16:00:00+08:00',
    venue: 'CCF Main, Mission Room',
    is_online: false,
    cost: 'Free',
    capacity: 50,
    registration_link: 'https://ccf.org.ph/across',
    contact_person: 'Ptr. Dan Ocampo',
    contact_number: '+639241234567',
    next_step_type: 'register_online',
    is_featured: false,
    status: 'Published',
  },
  {
    id: 'EVT-008',
    title: 'Kids Church Sunday',
    description: 'Worship and Bible lessons for kids ages 4-12, running parallel to main service.',
    ministry: 'NextGen',
    division: 'Ministries',
    journey_stage: 'Edify',
    start_datetime: '2026-05-17T09:00:00+08:00',
    end_datetime: '2026-05-17T10:30:00+08:00',
    venue: 'CCF Main, Kids Wing',
    is_online: false,
    cost: 'Free',
    capacity: 300,
    contact_person: 'Teacher Joy',
    contact_number: '+639191234567',
    next_step_type: 'walk_in',
    is_featured: false,
    status: 'Published',
  },
];

export const MOCK_PA_REPS: PastoralRep[] = [
  { rep_id: 'REP-001', pastoral_area: 'Ptr Erwin Elevazo PA', rep_name: 'Ate Cha Reyes',     rep_contact: '+639231234567', on_call_today: true },
  { rep_id: 'REP-002', pastoral_area: 'Ptr Bert Vila PA',     rep_name: 'Kuya Jun Mendoza',  rep_contact: '+639331234567', on_call_today: true },
];
